package cn.blooming.jxgjsj.model.mapper;

import cn.blooming.jxgjsj.model.entity.DecorationStype;
import cn.blooming.jxgjsj.model.entity.DecorationStypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DecorationStypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_stype
     *
     * @mbggenerated Mon Jul 15 09:45:11 CST 2019
     */
    int countByExample(DecorationStypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_stype
     *
     * @mbggenerated Mon Jul 15 09:45:11 CST 2019
     */
    int deleteByExample(DecorationStypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_stype
     *
     * @mbggenerated Mon Jul 15 09:45:11 CST 2019
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_stype
     *
     * @mbggenerated Mon Jul 15 09:45:11 CST 2019
     */
    int insert(DecorationStype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_stype
     *
     * @mbggenerated Mon Jul 15 09:45:11 CST 2019
     */
    int insertSelective(DecorationStype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_stype
     *
     * @mbggenerated Mon Jul 15 09:45:11 CST 2019
     */
    List<DecorationStype> selectByExample(DecorationStypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_stype
     *
     * @mbggenerated Mon Jul 15 09:45:11 CST 2019
     */
    DecorationStype selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_stype
     *
     * @mbggenerated Mon Jul 15 09:45:11 CST 2019
     */
    int updateByExampleSelective(@Param("record") DecorationStype record, @Param("example") DecorationStypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_stype
     *
     * @mbggenerated Mon Jul 15 09:45:11 CST 2019
     */
    int updateByExample(@Param("record") DecorationStype record, @Param("example") DecorationStypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_stype
     *
     * @mbggenerated Mon Jul 15 09:45:11 CST 2019
     */
    int updateByPrimaryKeySelective(DecorationStype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_stype
     *
     * @mbggenerated Mon Jul 15 09:45:11 CST 2019
     */
    int updateByPrimaryKey(DecorationStype record);
}