package cn.blooming.jxgjsj.model.mapper;

import cn.blooming.jxgjsj.model.entity.DecorationStypeDetails;
import cn.blooming.jxgjsj.model.entity.DecorationStypeDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DecorationStypeDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_stype_details
     *
     * @mbggenerated Mon Jul 15 09:42:17 CST 2019
     */
    int countByExample(DecorationStypeDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_stype_details
     *
     * @mbggenerated Mon Jul 15 09:42:17 CST 2019
     */
    int deleteByExample(DecorationStypeDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_stype_details
     *
     * @mbggenerated Mon Jul 15 09:42:17 CST 2019
     */
    int deleteByPrimaryKey(Integer did);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_stype_details
     *
     * @mbggenerated Mon Jul 15 09:42:17 CST 2019
     */
    int insert(DecorationStypeDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_stype_details
     *
     * @mbggenerated Mon Jul 15 09:42:17 CST 2019
     */
    int insertSelective(DecorationStypeDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_stype_details
     *
     * @mbggenerated Mon Jul 15 09:42:17 CST 2019
     */
    List<DecorationStypeDetails> selectByExample(DecorationStypeDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_stype_details
     *
     * @mbggenerated Mon Jul 15 09:42:17 CST 2019
     */
    DecorationStypeDetails selectByPrimaryKey(Integer did);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_stype_details
     *
     * @mbggenerated Mon Jul 15 09:42:17 CST 2019
     */
    int updateByExampleSelective(@Param("record") DecorationStypeDetails record, @Param("example") DecorationStypeDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_stype_details
     *
     * @mbggenerated Mon Jul 15 09:42:17 CST 2019
     */
    int updateByExample(@Param("record") DecorationStypeDetails record, @Param("example") DecorationStypeDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_stype_details
     *
     * @mbggenerated Mon Jul 15 09:42:17 CST 2019
     */
    int updateByPrimaryKeySelective(DecorationStypeDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_stype_details
     *
     * @mbggenerated Mon Jul 15 09:42:17 CST 2019
     */
    int updateByPrimaryKey(DecorationStypeDetails record);
}