package cn.blooming.jxgjsj.model.mapper;

import cn.blooming.jxgjsj.model.entity.House;
import cn.blooming.jxgjsj.model.entity.HouseExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface HouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Thu Aug 15 09:33:04 CST 2019
     */
    int countByExample(HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Thu Aug 15 09:33:04 CST 2019
     */
    int deleteByExample(HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Thu Aug 15 09:33:04 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Thu Aug 15 09:33:04 CST 2019
     */
    int insert(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Thu Aug 15 09:33:04 CST 2019
     */
    int insertSelective(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Thu Aug 15 09:33:04 CST 2019
     */
    List<House> selectByExample(HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Thu Aug 15 09:33:04 CST 2019
     */
    House selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Thu Aug 15 09:33:04 CST 2019
     */
    int updateByExampleSelective(@Param("record") House record, @Param("example") HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Thu Aug 15 09:33:04 CST 2019
     */
    int updateByExample(@Param("record") House record, @Param("example") HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Thu Aug 15 09:33:04 CST 2019
     */
    int updateByPrimaryKeySelective(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Thu Aug 15 09:33:04 CST 2019
     */
    int updateByPrimaryKey(House record);
}