package cn.blooming.jxgjsj.model.mapper;

import cn.blooming.jxgjsj.model.entity.HouseType;
import cn.blooming.jxgjsj.model.entity.HouseTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HouseTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Thu Aug 15 09:32:45 CST 2019
     */
    int countByExample(HouseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Thu Aug 15 09:32:45 CST 2019
     */
    int deleteByExample(HouseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Thu Aug 15 09:32:45 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Thu Aug 15 09:32:45 CST 2019
     */
    int insert(HouseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Thu Aug 15 09:32:45 CST 2019
     */
    int insertSelective(HouseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Thu Aug 15 09:32:45 CST 2019
     */
    List<HouseType> selectByExample(HouseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Thu Aug 15 09:32:45 CST 2019
     */
    HouseType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Thu Aug 15 09:32:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") HouseType record, @Param("example") HouseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Thu Aug 15 09:32:45 CST 2019
     */
    int updateByExample(@Param("record") HouseType record, @Param("example") HouseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Thu Aug 15 09:32:45 CST 2019
     */
    int updateByPrimaryKeySelective(HouseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_type
     *
     * @mbggenerated Thu Aug 15 09:32:45 CST 2019
     */
    int updateByPrimaryKey(HouseType record);
}