package cn.blooming.jxgjsj.model.entity;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.io.Serializable;

@ToString
@Getter
@Setter
public class Community implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.id
     *
     * @mbggenerated Thu Aug 15 09:34:29 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.name
     *
     * @mbggenerated Thu Aug 15 09:34:29 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.addr
     *
     * @mbggenerated Thu Aug 15 09:34:29 CST 2019
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.info
     *
     * @mbggenerated Thu Aug 15 09:34:29 CST 2019
     */
    private String info;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.id
     *
     * @return the value of community.id
     *
     * @mbggenerated Thu Aug 15 09:34:29 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.id
     *
     * @param id the value for community.id
     *
     * @mbggenerated Thu Aug 15 09:34:29 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.name
     *
     * @return the value of community.name
     *
     * @mbggenerated Thu Aug 15 09:34:29 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.name
     *
     * @param name the value for community.name
     *
     * @mbggenerated Thu Aug 15 09:34:29 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.addr
     *
     * @return the value of community.addr
     *
     * @mbggenerated Thu Aug 15 09:34:29 CST 2019
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.addr
     *
     * @param addr the value for community.addr
     *
     * @mbggenerated Thu Aug 15 09:34:29 CST 2019
     */
    public void setAddr(String addr) {
        this.addr = addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.info
     *
     * @return the value of community.info
     *
     * @mbggenerated Thu Aug 15 09:34:29 CST 2019
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.info
     *
     * @param info the value for community.info
     *
     * @mbggenerated Thu Aug 15 09:34:29 CST 2019
     */
    public void setInfo(String info) {
        this.info = info;
    }
}