package cn.blooming.jxgjsj.model.entity;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.io.Serializable;

@ToString
@Getter
@Setter
public class DecorationStypeDetails implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_stype_details.did
     *
     * @mbggenerated Mon Jul 15 09:42:17 CST 2019
     */
    private Integer did;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_stype_details.name
     *
     * @mbggenerated Mon Jul 15 09:42:17 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_stype_details.sid
     *
     * @mbggenerated Mon Jul 15 09:42:17 CST 2019
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_stype_details.uid
     *
     * @mbggenerated Mon Jul 15 09:42:17 CST 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_stype_details.dinfo
     *
     * @mbggenerated Mon Jul 15 09:42:17 CST 2019
     */
    private String dinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_stype_details.hid
     *
     * @mbggenerated Mon Jul 15 09:42:17 CST 2019
     */
    private Integer hid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_stype_details.did
     *
     * @return the value of decoration_stype_details.did
     *
     * @mbggenerated Mon Jul 15 09:42:17 CST 2019
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_stype_details.did
     *
     * @param did the value for decoration_stype_details.did
     *
     * @mbggenerated Mon Jul 15 09:42:17 CST 2019
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_stype_details.name
     *
     * @return the value of decoration_stype_details.name
     *
     * @mbggenerated Mon Jul 15 09:42:17 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_stype_details.name
     *
     * @param name the value for decoration_stype_details.name
     *
     * @mbggenerated Mon Jul 15 09:42:17 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_stype_details.sid
     *
     * @return the value of decoration_stype_details.sid
     *
     * @mbggenerated Mon Jul 15 09:42:17 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_stype_details.sid
     *
     * @param sid the value for decoration_stype_details.sid
     *
     * @mbggenerated Mon Jul 15 09:42:17 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_stype_details.uid
     *
     * @return the value of decoration_stype_details.uid
     *
     * @mbggenerated Mon Jul 15 09:42:17 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_stype_details.uid
     *
     * @param uid the value for decoration_stype_details.uid
     *
     * @mbggenerated Mon Jul 15 09:42:17 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_stype_details.dinfo
     *
     * @return the value of decoration_stype_details.dinfo
     *
     * @mbggenerated Mon Jul 15 09:42:17 CST 2019
     */
    public String getDinfo() {
        return dinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_stype_details.dinfo
     *
     * @param dinfo the value for decoration_stype_details.dinfo
     *
     * @mbggenerated Mon Jul 15 09:42:17 CST 2019
     */
    public void setDinfo(String dinfo) {
        this.dinfo = dinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_stype_details.hid
     *
     * @return the value of decoration_stype_details.hid
     *
     * @mbggenerated Mon Jul 15 09:42:17 CST 2019
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_stype_details.hid
     *
     * @param hid the value for decoration_stype_details.hid
     *
     * @mbggenerated Mon Jul 15 09:42:17 CST 2019
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }
}