package cn.blooming.jxgjsj.model.entity;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.io.Serializable;

@ToString
@Getter
@Setter
public class DecorationStype implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_stype.sid
     *
     * @mbggenerated Mon Jul 15 09:45:11 CST 2019
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_stype.sname
     *
     * @mbggenerated Mon Jul 15 09:45:11 CST 2019
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_stype.spath
     *
     * @mbggenerated Mon Jul 15 09:45:11 CST 2019
     */
    private String spath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_stype.did
     *
     * @mbggenerated Mon Jul 15 09:45:11 CST 2019
     */
    private Integer did;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_stype.sid
     *
     * @return the value of decoration_stype.sid
     *
     * @mbggenerated Mon Jul 15 09:45:11 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_stype.sid
     *
     * @param sid the value for decoration_stype.sid
     *
     * @mbggenerated Mon Jul 15 09:45:11 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_stype.sname
     *
     * @return the value of decoration_stype.sname
     *
     * @mbggenerated Mon Jul 15 09:45:11 CST 2019
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_stype.sname
     *
     * @param sname the value for decoration_stype.sname
     *
     * @mbggenerated Mon Jul 15 09:45:11 CST 2019
     */
    public void setSname(String sname) {
        this.sname = sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_stype.spath
     *
     * @return the value of decoration_stype.spath
     *
     * @mbggenerated Mon Jul 15 09:45:11 CST 2019
     */
    public String getSpath() {
        return spath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_stype.spath
     *
     * @param spath the value for decoration_stype.spath
     *
     * @mbggenerated Mon Jul 15 09:45:11 CST 2019
     */
    public void setSpath(String spath) {
        this.spath = spath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_stype.did
     *
     * @return the value of decoration_stype.did
     *
     * @mbggenerated Mon Jul 15 09:45:11 CST 2019
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_stype.did
     *
     * @param did the value for decoration_stype.did
     *
     * @mbggenerated Mon Jul 15 09:45:11 CST 2019
     */
    public void setDid(Integer did) {
        this.did = did;
    }
}