package cn.blooming.jxgjsj.model.entity;

import java.io.Serializable;

public class House implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.id
     *
     * @mbggenerated Fri Jul 12 16:50:35 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.uid
     *
     * @mbggenerated Fri Jul 12 16:50:35 CST 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.sid
     *
     * @mbggenerated Fri Jul 12 16:50:35 CST 2019
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.type
     *
     * @mbggenerated Fri Jul 12 16:50:35 CST 2019
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.money
     *
     * @mbggenerated Fri Jul 12 16:50:35 CST 2019
     */
    private Long money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.size
     *
     * @mbggenerated Fri Jul 12 16:50:35 CST 2019
     */
    private Long size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.community
     *
     * @mbggenerated Fri Jul 12 16:50:35 CST 2019
     */
    private Integer community;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.price
     *
     * @mbggenerated Fri Jul 12 16:50:35 CST 2019
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.hinfo
     *
     * @mbggenerated Fri Jul 12 16:50:35 CST 2019
     */
    private String hinfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.id
     *
     * @return the value of house.id
     *
     * @mbggenerated Fri Jul 12 16:50:35 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.id
     *
     * @param id the value for house.id
     *
     * @mbggenerated Fri Jul 12 16:50:35 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.uid
     *
     * @return the value of house.uid
     *
     * @mbggenerated Fri Jul 12 16:50:35 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.uid
     *
     * @param uid the value for house.uid
     *
     * @mbggenerated Fri Jul 12 16:50:35 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.sid
     *
     * @return the value of house.sid
     *
     * @mbggenerated Fri Jul 12 16:50:35 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.sid
     *
     * @param sid the value for house.sid
     *
     * @mbggenerated Fri Jul 12 16:50:35 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.type
     *
     * @return the value of house.type
     *
     * @mbggenerated Fri Jul 12 16:50:35 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.type
     *
     * @param type the value for house.type
     *
     * @mbggenerated Fri Jul 12 16:50:35 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.money
     *
     * @return the value of house.money
     *
     * @mbggenerated Fri Jul 12 16:50:35 CST 2019
     */
    public Long getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.money
     *
     * @param money the value for house.money
     *
     * @mbggenerated Fri Jul 12 16:50:35 CST 2019
     */
    public void setMoney(Long money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.size
     *
     * @return the value of house.size
     *
     * @mbggenerated Fri Jul 12 16:50:35 CST 2019
     */
    public Long getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.size
     *
     * @param size the value for house.size
     *
     * @mbggenerated Fri Jul 12 16:50:35 CST 2019
     */
    public void setSize(Long size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.community
     *
     * @return the value of house.community
     *
     * @mbggenerated Fri Jul 12 16:50:35 CST 2019
     */
    public Integer getCommunity() {
        return community;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.community
     *
     * @param community the value for house.community
     *
     * @mbggenerated Fri Jul 12 16:50:35 CST 2019
     */
    public void setCommunity(Integer community) {
        this.community = community;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.price
     *
     * @return the value of house.price
     *
     * @mbggenerated Fri Jul 12 16:50:35 CST 2019
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.price
     *
     * @param price the value for house.price
     *
     * @mbggenerated Fri Jul 12 16:50:35 CST 2019
     */
    public void setPrice(String price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.hinfo
     *
     * @return the value of house.hinfo
     *
     * @mbggenerated Fri Jul 12 16:50:35 CST 2019
     */
    public String getHinfo() {
        return hinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.hinfo
     *
     * @param hinfo the value for house.hinfo
     *
     * @mbggenerated Fri Jul 12 16:50:35 CST 2019
     */
    public void setHinfo(String hinfo) {
        this.hinfo = hinfo;
    }
}