package cn.blooming.jxgjsj.model.entity;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.io.Serializable;

@ToString
@Getter
@Setter
public class HouseType implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type.id
     *
     * @mbggenerated Fri Jul 12 11:27:37 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_type.type
     *
     * @mbggenerated Fri Jul 12 11:27:37 CST 2019
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type.id
     *
     * @return the value of house_type.id
     *
     * @mbggenerated Fri Jul 12 11:27:37 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type.id
     *
     * @param id the value for house_type.id
     *
     * @mbggenerated Fri Jul 12 11:27:37 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_type.type
     *
     * @return the value of house_type.type
     *
     * @mbggenerated Fri Jul 12 11:27:37 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_type.type
     *
     * @param type the value for house_type.type
     *
     * @mbggenerated Fri Jul 12 11:27:37 CST 2019
     */
    public void setType(String type) {
        this.type = type;
    }
}