package cn.blooming.jxgjsj.model.entity;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.io.Serializable;

@ToString
@Getter
@Setter
public class Menu implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.mid
     *
     * @mbggenerated Thu Aug 15 09:30:44 CST 2019
     */
    private Integer mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.mname
     *
     * @mbggenerated Thu Aug 15 09:30:44 CST 2019
     */
    private String mname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.mpath
     *
     * @mbggenerated Thu Aug 15 09:30:44 CST 2019
     */
    private String mpath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.mid
     *
     * @return the value of menu.mid
     *
     * @mbggenerated Thu Aug 15 09:30:44 CST 2019
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.mid
     *
     * @param mid the value for menu.mid
     *
     * @mbggenerated Thu Aug 15 09:30:44 CST 2019
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.mname
     *
     * @return the value of menu.mname
     *
     * @mbggenerated Thu Aug 15 09:30:44 CST 2019
     */
    public String getMname() {
        return mname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.mname
     *
     * @param mname the value for menu.mname
     *
     * @mbggenerated Thu Aug 15 09:30:44 CST 2019
     */
    public void setMname(String mname) {
        this.mname = mname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.mpath
     *
     * @return the value of menu.mpath
     *
     * @mbggenerated Thu Aug 15 09:30:44 CST 2019
     */
    public String getMpath() {
        return mpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.mpath
     *
     * @param mpath the value for menu.mpath
     *
     * @mbggenerated Thu Aug 15 09:30:44 CST 2019
     */
    public void setMpath(String mpath) {
        this.mpath = mpath;
    }
}