package cn.blooming.jxgjsj.model.mapper;

import cn.blooming.jxgjsj.model.entity.Community;
import cn.blooming.jxgjsj.model.entity.CommunityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommunityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community
     *
     * @mbggenerated Tue Jul 14 15:42:21 CST 2020
     */
    int countByExample(CommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community
     *
     * @mbggenerated Tue Jul 14 15:42:21 CST 2020
     */
    int deleteByExample(CommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community
     *
     * @mbggenerated Tue Jul 14 15:42:21 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community
     *
     * @mbggenerated Tue Jul 14 15:42:21 CST 2020
     */
    int insert(Community record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community
     *
     * @mbggenerated Tue Jul 14 15:42:21 CST 2020
     */
    int insertSelective(Community record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community
     *
     * @mbggenerated Tue Jul 14 15:42:21 CST 2020
     */
    List<Community> selectByExample(CommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community
     *
     * @mbggenerated Tue Jul 14 15:42:21 CST 2020
     */
    Community selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community
     *
     * @mbggenerated Tue Jul 14 15:42:21 CST 2020
     */
    int updateByExampleSelective(@Param("record") Community record, @Param("example") CommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community
     *
     * @mbggenerated Tue Jul 14 15:42:21 CST 2020
     */
    int updateByExample(@Param("record") Community record, @Param("example") CommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community
     *
     * @mbggenerated Tue Jul 14 15:42:21 CST 2020
     */
    int updateByPrimaryKeySelective(Community record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community
     *
     * @mbggenerated Tue Jul 14 15:42:21 CST 2020
     */
    int updateByPrimaryKey(Community record);
}